---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
      - path: metadata/name
        kind: Namespace
        create: true

components:
  - ../../lib/networking/metallb
  - ../../lib/networking/netconfig
  - ../../lib/networking/nad
  - ../../lib/control-plane

resources:
  - nad.yaml

patches:
  - target:
      version: v1beta1
      kind: NetConfig
      name: netconfig
    patch: |-
      - op: add
        path: /spec/networks/-
        value:
          dnsDomain: _replaced_
          name: storagemgmt
          subnets:
            - _replaced_
          mtu: 1500

replacements:
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.storagemgmt.dnsDomain
    targets:
      - select:
          kind: NetConfig
        fieldPaths:
          - spec.networks.[name=storagemgmt].dnsDomain

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.storagemgmt.mtu
    targets:
      - select:
          kind: NetConfig
        fieldPaths:
          - spec.networks.[name=storagemgmt].mtu

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.storagemgmt.subnets
    targets:
      - select:
          kind: NetConfig
        fieldPaths:
          - spec.networks.[name=storagemgmt].subnets

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.neutron.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.neutron.template.customServiceConfig
        options:
          create: true

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.ironic.net-attach-def
    targets:
      - select:
          kind: NetworkAttachmentDefinition
          name: ironic
        fieldPaths:
          - spec.config

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.ironic.rpcTransport
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.ironic.template.rpcTransport
        options:
          create: true

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.ctlplane.endpoint_annotations
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.ironic.template.ironicAPI.override.service.internal.metadata.annotations
        options:
          create: true

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.ctlplane.endpoint_annotations
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.ironic.template.ironicInspector.override.service.internal.metadata.annotations
        options:
          create: true

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.lbServiceType
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.ironic.template.ironicAPI.override.service.internal.spec.type
          - spec.ironic.template.ironicInspector.override.service.internal.spec.type
        options:
          create: true

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.ironic.iface
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.ironic.template.ironicConductors.0.networkAttachments.0
          - spec.ironic.template.ironicConductors.0.provisionNetwork
          - spec.ironic.template.ironicInspector.inspectionNetwork
          - spec.ironic.template.ironicInspector.networkAttachments.0
          - spec.ovn.template.ovnController.nicMappings.ironic
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.ironic.ironicConductors.0.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.ironic.template.ironicConductors.0.customServiceConfig
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.ironic.ironicInspector.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.ironic.template.ironicInspector.customServiceConfig
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.nova.cellTemplates
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.nova.template.cellTemplates
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.horizon.enabled
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.horizon.enabled
        options:
          create: true
