---
apiVersion: v1
kind: ConfigMap
metadata:
  name: baremetalhost-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  metal3_inspection: disabled
  edpm-compute-0:
    online: true
    labels:
      app: openstack
      nodeset: edpm
      nodeName: edpm-compute-0
    bmc:
      address: CHANGEME
      # NOTE: in CI systems, we use credentials_file from cifmw_baremetal_hosts.
      # credentialsName: bmc-secret
      disableCertificateVerification: true
    bootMACAddress: CHANGEME
    rootDeviceHints:
      deviceName: /dev/vda
    preprovisioningNetworkData:
      nmstate: |
        CHANGEME
