---
apiVersion: v1
kind: ConfigMap

metadata:
  name: service-values
  annotations:
    config.kubernetes.io/local-config: "true"

data:
  # --- Fields required by lib/control-plane ---
  preserveJobs: false
  notificationsBus:
    cluster: rabbitmq-notifications
  tls:
    caBundleSecretName: ""

  # --- Below are VA/DT-specific data ---
  cinderBackup:
    customServiceConfig: |
      [DEFAULT]
      backup_driver = cinder.backup.drivers.swift.SwiftBackupDriver
    replicas: 1

  cinderVolumes:
    ceph:
      customServiceConfig: |
        [ceph]
        volume_backend_name=ceph
        volume_driver=cinder.volume.drivers.rbd.RBDDriver
        rbd_ceph_conf=/etc/ceph/ceph.conf
        rbd_user=openstack
        rbd_pool=volumes
        rbd_flatten_volume_from_snapshot=False
        report_discard_supported=True
        rbd_secret_uuid = _replaced_
      networkAttachments:
        - storage
    nfs:
      customServiceConfig: |
        [nfs]
        volume_backend_name=nfs
        volume_driver=cinder.volume.drivers.nfs.NfsDriver
        nfs_snapshot_support=true
        nas_secure_file_operations=false
        nas_secure_file_permissions=false
      networkAttachments:
        - storage
      customServiceConfigSecrets:
        - cinder-volume-nfs-secrets
    ontap-iscsi:
      customServiceConfig: |
        [ontap]
        volume_backend_name=ontap
        volume_driver=cinder.volume.drivers.netapp.common.NetAppDriver
        netapp_server_hostname=_replaced_
        netapp_server_port=80
        netapp_storage_protocol=iscsi
        netapp_storage_family=ontap_cluster
        consistencygroup_support=True
      networkAttachments:
        - storage
      customServiceConfigSecrets:
        - cinder-volume-ontap-secrets
  cinder-volume-nfs-secrets: |
    [nas]
    nas_host = _replaced_
    nas_share_path = _replaced_
  cinder-volume-ontap-secrets: |
    [ontap]
    netapp_login = _replaced_
    netapp_password = _replaced_
    netapp_vserver = _replaced_

  extraMounts:
    - name: v1
      region: r1
      extraVol:
        - propagation:
            - CinderVolume
            - GlanceAPI
          extraVolType: Ceph
          mounts:
            - name: ceph
              mountPath: /etc/ceph
              readOnly: true
          volumes:
            - name: ceph
              projected:
                sources:
                  - secret:
                      name: ceph-conf-files

  galera:
    templates:
      openstack-cell2:
        storageRequest: 5G
        secret: osp-secret
        replicas: 3

  glance:
    customServiceConfig: |
      [DEFAULT]
      debug = True
      enabled_backends = primary:cinder,secondary:rbd,tertiary:swift
      [glance_store]
      default_backend = primary
      [primary]
      description = NFS based cinder store
      cinder_store_auth_address = {{ .KeystoneInternalURL }}
      cinder_store_user_name = {{ .ServiceUser }}
      cinder_store_password = {{ .ServicePassword }}
      cinder_store_project_name = service
      cinder_catalog_info = volumev3::internalURL
      cinder_use_multipath = true
      [secondary]
      store_description = RBD backend
      rbd_store_ceph_conf = /etc/ceph/ceph.conf
      rbd_store_pool = images
      rbd_store_user = openstack
      [tertiary]
      swift_store_create_container_on_put = True
      swift_store_auth_version = 3
      swift_store_auth_address = {{ .KeystoneInternalURL }}
      swift_store_endpoint_type = internalURL
      swift_store_user = service:glance
      swift_store_key = {{ .ServicePassword }}
      [oslo_concurrency]
      lock_path = /var/lib/glance/tmp
    databaseInstance: openstack
    glanceAPIs:
      default:
        replicas: 3
        type: split

  heat:
    enabled: true

  nova:
    template:
      cellTemplates:
        cell2:
          cellDatabaseAccount: nova-cell2
          cellDatabaseInstance: openstack-cell2
          messagingBus:
            cluster: rabbitmq-cell2
          conductorServiceTemplate:
            replicas: 1
          hasAPIAccess: true

  rabbitmq:
    templates:
      rabbitmq-cell2:
        replicas: 3
      rabbitmq-notifications:
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.88
            spec:
              type: LoadBalancer
        replicas: 3

  swift:
    enabled: true

  telemetry:
    enabled: true
    metricStorage:
      enabled: true
      monitoringStack: null
      customMonitoringStack:
        alertmanagerConfig:
          disabled: true
        prometheusConfig:
          enableRemoteWriteReceiver: true
          persistentVolumeClaim:
            resources:
              requests:
                storage: 20G
          replicas: 1
          scrapeInterval: 30s
        resourceSelector:
          matchLabels:
            service: metricStorage
        retention: 24h
    autoscaling:
      enabled: true
    ceilometer:
      enabled: true

  watcher:
    enabled: true
