---
apiVersion: v1
kind: ConfigMap

metadata:
  name: edpm-nodeset-values-post-ceph
  annotations:
    config.kubernetes.io/local-config: "true"

data:
  ceph:
    conf: _replaced_
    keyring: _replaced_

  nodeset:
    services:
      - bootstrap
      - download-cache
      - configure-network
      - install-os
      - validate-network
      - ceph-hci-pre
      - configure-os
      - ssh-known-hosts
      - run-os
      - reboot-os
      - install-certs
      - ceph-client
      - ovn
      - neutron-metadata
      - libvirt
      - nova-custom

  nova-extra-config: |
    # Additional overrides that can be set in environment-specific cases
