---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nodeset-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  network_config_template: &network_config_template |
    ---
    {% set mtu_list = [ctlplane_mtu] %}
    {% for network in nodeset_networks %}
    {{ mtu_list.append(lookup('vars', networks_lower[network] ~ '_mtu')) }}
    {%- endfor %}
    {% set min_viable_mtu = mtu_list | max %}
    network_config:
      - type: ovs_bridge
        name: {{ neutron_physical_bridge_name }}
        mtu: {{ min_viable_mtu }}
        use_dhcp: false
        dns_servers: {{ ctlplane_dns_nameservers }}
        domain: {{ dns_search_domains }}
        addresses:
          - ip_netmask: {{ ctlplane_ip }}/{{ ctlplane_cidr }}
        routes: {{ ctlplane_host_routes }}
        members:
          - type: interface
            name: nic1
            mtu: {{ min_viable_mtu }}
            primary: true
    {% for network in nodeset_networks %}
          - type: vlan
            mtu: {{ lookup('vars', networks_lower[network] ~ '_mtu') }}
            vlan_id: {{ lookup('vars', networks_lower[network] ~ '_vlan_id') }}
            addresses:
              - ip_netmask: >-
                  {{
                    lookup('vars', networks_lower[network] ~ '_ip')
                  }}/{{
                    lookup('vars', networks_lower[network] ~ '_cidr')
                  }}
            routes: {{ lookup('vars', networks_lower[network] ~ '_host_routes') }}
    {% endfor %}

  nodeset0:
    ctlplaneInterface: enp5s0
    neutron_physical_bridge_name: br-ex
    neutron_public_interface_name: enp5s0
    edpm_ovn_bridge_mappings:
      - "datacentre_leaf0:br-ex"
    edpm_network_config_template: *network_config_template
    edpm_sshd_allowed_ranges:
      - 192.168.122.0/24
      - 192.168.123.0/24
      - 192.168.124.0/24
      - 192.168.32.9/20
    timesync_ntp_servers:
      - hostname: pool.ntp.org
    edpm_bootstrap_command: |
      # _replace_
      echo "Bootstrap script."
    baremetalHostsNetworkData:
      edpm-compute-0-0:
        networkData: |
          links:
            - name: enp5s0
              id: enp5s0
              type: vif
          networks:
            - link: enp5s0
              id: enp5s0
              type: ipv4
              network_id: enp5s0
              ip_address: 192.168.123.100
              netmask: 255.255.255.0
              routes:
                - network: 0.0.0.0
                  netmask: 0.0.0.0
                  gateway: 192.168.123.1
          services:
            - type: dns
              address: 192.168.122.1
      edpm-compute-0-1:
        networkData: |
          links:
            - name: enp5s0
              id: enp5s0
              type: vif
          networks:
            - link: enp5s0
              id: enp5s0
              type: ipv4
              network_id: enp5s0
              ip_address: 192.168.123.101
              netmask: 255.255.255.0
              routes:
                - network: 0.0.0.0
                  netmask: 0.0.0.0
                  gateway: 192.168.123.1
          services:
            - type: dns
              address: 192.168.122.1
    nodes:
      edpm-compute-0-0:
        networkData:
          name: edpm-compute-0-0-network-data
          namespace: openstack
        ansible:
          ansibleHost: 192.168.123.100
        hostName: edpm-compute-0-0
        networks:
          - defaultRoute: true
            fixedIP: 192.168.123.100
            name: ctlplane
            subnetName: subnet2
          - name: internalapi
            subnetName: subnet2
          - name: storage
            subnetName: subnet2
          - name: tenant
            subnetName: subnet2
      edpm-compute-0-1:
        networkData:
          name: edpm-compute-0-1-network-data
          namespace: openstack
        ansible:
          ansibleHost: 192.168.123.101
        hostName: edpm-compute-0-1
        networks:
          - defaultRoute: true
            fixedIP: 192.168.123.101
            name: ctlplane
            subnetName: subnet2
          - name: internalapi
            subnetName: subnet2
          - name: storage
            subnetName: subnet2
          - name: tenant
            subnetName: subnet2

  nodeset1:
    ctlplaneInterface: enp5s0
    neutron_physical_bridge_name: br-ex
    neutron_public_interface_name: enp5s0
    edpm_ovn_bridge_mappings:
      - "datacentre_leaf1:br-ex"
    edpm_network_config_template: *network_config_template
    edpm_sshd_allowed_ranges:
      - 192.168.122.0/24
      - 192.168.123.0/24
      - 192.168.124.0/24
      - 192.168.32.9/20
    timesync_ntp_servers:
      - hostname: pool.ntp.org
    edpm_bootstrap_command: |
      # _replace_
      echo "Bootstrap script."
    baremetalHostsNetworkData:
      edpm-compute-1-0:
        networkData: |
          links:
            - name: enp5s0
              id: enp5s0
              type: vif
          networks:
            - link: enp5s0
              id: enp5s0
              type: ipv4
              network_id: enp5s0
              ip_address: 192.168.124.100
              netmask: 255.255.255.0
              routes:
                - network: 0.0.0.0
                  netmask: 0.0.0.0
                  gateway: 192.168.124.1
          services:
            - type: dns
              address: 192.168.122.1
      edpm-compute-1-1:
        networkData: |
          links:
            - name: enp5s0
              id: enp5s0
              type: vif
          networks:
            - link: enp5s0
              id: enp5s0
              type: ipv4
              network_id: enp5s0
              ip_address: 192.168.124.101
              netmask: 255.255.255.0
              routes:
                - network: 0.0.0.0
                  netmask: 0.0.0.0
                  gateway: 192.168.124.1
          services:
            - type: dns
              address: 192.168.122.1
    nodes:
      edpm-compute-1-0:
        networkData:
          name: edpm-compute-1-0-network-data
          namespace: openstack
        ansible:
          ansibleHost: 192.168.124.100
        hostName: edpm-compute-1-0
        networks:
          - defaultRoute: true
            fixedIP: 192.168.124.100
            name: ctlplane
            subnetName: subnet3
          - name: internalapi
            subnetName: subnet3
          - name: storage
            subnetName: subnet3
          - name: tenant
            subnetName: subnet3
      edpm-compute-1-1:
        networkData:
          name: edpm-compute-1-1-network-data
          namespace: openstack
        ansible:
          ansibleHost: 192.168.124.101
        hostName: edpm-compute-1-1
        networks:
          - defaultRoute: true
            fixedIP: 192.168.124.101
            name: ctlplane
            subnetName: subnet3
          - name: internalapi
            subnetName: subnet3
          - name: storage
            subnetName: subnet3
          - name: tenant
            subnetName: subnet3
