---
apiVersion: v1
kind: ConfigMap

metadata:
  name: service-values
  annotations:
    config.kubernetes.io/local-config: "true"

data:
  # --- Fields required by lib/control-plane ---
  preserveJobs: false
  tls:
    caBundleSecretName: ""

  # --- Below are VA/DT-specific data ---
  cinderVolumes:
    lvm-nvme-tcp:
      replicas: 1
      nodeSelector:
        kubernetes.io/hostname: master-0
      customServiceConfig: |
        [lvm]
        volume_backend_name=lvm_nvme_tcp
        volume_driver=cinder.volume.drivers.lvm.LVMVolumeDriver
        target_helper=nvmet
        target_protocol=nvmet_tcp
        target_port=4420
        target_prefix=nvme-subsystem-1
        nvmeof_conn_info_version=2
        target_ip_address=172.18.0.10
        target_secondary_ip_addresses = 172.19.0.10

  cinderBackup:
    customServiceConfig: |
      [DEFAULT]
      backup_driver = cinder.backup.drivers.swift.SwiftBackupDriver
      backup_compression_algorithm = zstd
      backup_s3_endpoint_url = https://swift-public-openstack.apps.ocp.openstack.lab/
      backup_s3_store_access_key = 401e5f2c73eb45d3b0256dc8dbe65cf5
      backup_s3_store_secret_key = 6032b0bbcced409d955568be27382c44
      backup_s3_store_bucket = volumebackups
      backup_s3_ca_cert_file = /etc/pki/tls/certs/ca-bundle.crt
      backup_driver = cinder.backup.drivers.s3.S3BackupDriver
    replicas: 1

  glance:
    customServiceConfig: |
      [DEFAULT]
      debug = True
      enabled_backends = default_backend:cinder
      [glance_store]
      default_backend = default_backend
      [default_backend]
      description = Default cinder backend
      cinder_store_auth_address = {{ .KeystoneInternalURL }}
      cinder_store_user_name = {{ .ServiceUser }}
      cinder_store_password = {{ .ServicePassword }}
      cinder_store_project_name = service
      cinder_catalog_info = volumev3::internalURL
      cinder_use_multipath = true
      [oslo_concurrency]
      lock_path = /var/lib/glance/tmp
    default:
      replicas: 3

  swift:
    enabled: true
    swiftProxy:
      replicas: 1
    swiftStorage:
      replicas: 1
    swiftRing:
      ringReplicas: 1

  heat:
    enabled: true

  octavia:
    enabled: true
    amphoraImageContainerImage: quay.io/gthiemonge/octavia-amphora-image
    apacheContainerImage: registry.redhat.io/ubi9/httpd-24:latest
    availabilityZones:
      - zone-1
    octaviaAPI:
      networkAttachments:
        - internalapi
    octaviaHousekeeping:
      networkAttachments:
        - octavia
    octaviaHealthManager:
      networkAttachments:
        - octavia
    octaviaWorker:
      networkAttachments:
        - octavia

  ovn:
    ovnController:
      nicMappings:
        octavia: octbr
        datacentre: ocpbr
      availability-zones:
        - zone-1

  neutron:
    customServiceConfig: |
      [DEFAULT]
      dns_domain = openstackgate.local
      vlan_transparent = true
      service_plugins = ovn-router,qos,segments,trunk,port_forwarding
      dhcp_agent_notification = false
      agent_down_time = 600
      router_distributed = false
      enable_dvr = false
      router_scheduler_driver = neutron.scheduler.l3_agent_scheduler.ChanceScheduler
      allow_automatic_l3agent_failover = true
      l3_ha = False
      max_l3_agents_per_router = 3
      debug = true
      control_exchange = neutron
      [agent]
      report_interval = 300
      [database]
      max_retries = -1
      db_max_retries = -1
      [keystone_authtoken]
      region_name = regionOne
      memcache_use_advanced_pool = True
      auth_type = password
      [nova]
      region_name = regionOne
      endpoint_type = internal
      [oslo_messaging_notifications]
      driver = noop
      [oslo_middleware]
      enable_proxy_headers_parsing = true
      [oslo_policy]
      policy_file = /etc/neutron/policy.yaml
      [placement]
      region_name = regionOne
      [ovs]
      igmp_snooping_enable = true
      [ovn]
      ovn_emit_need_to_frag = true
      enable_distributed_floating_ip = false
      [ml2]
      type_drivers = geneve,vlan,flat,local
      tenant_network_types = geneve,vlan
      extension_drivers = qos,port_security,dns_domain_ports
      path_mtu = 1400
      [ml2_type_geneve]
      vni_ranges = 1:65536
      max_header_size = 38
      [ml2_type_vlan]
      network_vlan_ranges = tenant:1000:2000,datacentre:218:218
