apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneDeployment
metadata:
  name: openstack-edpm-ipam
  namespace: openstack
spec:
  nodeSets:
  - openstack-edpm-ipam
  servicesOverride:
    - ceph-client
    - ovn
    - neutron-metadata
    - libvirt
    - nova-custom-ceph
