---
apiVersion: v1
kind: ConfigMap

metadata:
  name: dataplane-secret-values
  annotations:
    config.kubernetes.io/local-config: "true"

data:
  ssh_keys:
    authorized: _replaced_
    private: _replaced_
    public: _replaced_

  nova:
    migration:
      ssh_keys:
        private: _replaced_
        public: _replaced_kustomization.yaml
