---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
  - name: octavia-ca-passphrase
    literals:
      - server-ca-passphrase=12345678
    options:
      disableNameSuffixHash: true

transformers:
  - |-
      apiVersion: builtin
      kind: NamespaceTransformer
      metadata:
        name: _ignored_
        namespace: openstack
      setRoleBindingSubjects: none
      unsetOnly: true
      fieldSpecs:
        - path: metadata/name
          kind: Namespace
          create: true

components:
  - ../../lib/control-plane


replacements:
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinderVolumes.lvm-iscsi.replicas
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.cinder.template.cinderVolumes.lvm-iscsi.replicas
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinderVolumes.lvm-iscsi.nodeSelector.openstack\.org/cinder-lvm
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.cinder.template.cinderVolumes.lvm-iscsi.nodeSelector.openstack\.org/cinder-lvm
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinderVolumes.lvm-iscsi.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.cinder.template.cinderVolumes.lvm-iscsi.customServiceConfig
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinderBackup.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.cinder.template.cinderBackup.customServiceConfig
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinderBackup.replicas
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.cinder.template.cinderBackup.replicas
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.glance.default.replicas
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.glance.template.glanceAPIs.default.replicas
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.glance.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.glance.template.customServiceConfig
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.glance.default.replicas
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.glance.template.glanceAPIs.default.replicas
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.swift.enabled
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.swift.enabled
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.ironic.enabled
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.ironic.enabled
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.ironic.rpcTransport
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.ironic.template.rpcTransport
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.octavia.enabled
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.octavia.enabled
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.octavia.amphoraImageContainerImage
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.octavia.template.amphoraImageContainerImage
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.octavia.apacheContainerImage
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.octavia.template.apacheContainerImage
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.octavia.availabilityZones
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.octavia.template.lbMgmtNetwork.availabilityZones
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.octavia.octaviaAPI.networkAttachments
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.octavia.template.octaviaAPI.networkAttachments
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.octavia.octaviaHousekeeping.networkAttachments
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.octavia.template.octaviaHousekeeping.networkAttachments
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.octavia.octaviaHealthManager.networkAttachments
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.octavia.template.octaviaHealthManager.networkAttachments
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.octavia.octaviaWorker.networkAttachments
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.octavia.template.octaviaWorker.networkAttachments
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.octavia.redisServiceName
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.octavia.template.redisServiceName
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.redis.enabled
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.redis.enabled
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.redis.templates
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.redis.templates
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.heat.enabled
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.heat.enabled
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.heat.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.heat.template.customServiceConfig
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.telemetry.enabled
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.telemetry.enabled
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.telemetry.metricStorage.enabled
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.telemetry.template.metricStorage.enabled
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.telemetry.autoscaling.enabled
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.telemetry.template.autoscaling.enabled
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.telemetry.ceilometer.enabled
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.telemetry.template.ceilometer.enabled
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.ovn.ovnController.availability-zones
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.ovn.template.ovnController.external-ids.availability-zones
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.ovn.ovnController.nicMappings
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.ovn.template.ovnController.nicMappings
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.neutron.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.neutron.template.customServiceConfig
        options:
          create: true

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.ctlplane.endpoint_annotations
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.ironic.template.ironicAPI.override.service.internal.metadata.annotations
        options:
          create: true

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.ctlplane.endpoint_annotations
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.ironic.template.ironicInspector.override.service.internal.metadata.annotations
        options:
          create: true

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.lbServiceType
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.ironic.template.ironicAPI.override.service.internal.spec.type
          - spec.ironic.template.ironicInspector.override.service.internal.spec.type
        options:
          create: true

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.ironic.iface
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.ironic.template.ironicConductors.0.networkAttachments.0
          - spec.ironic.template.ironicConductors.0.provisionNetwork
          - spec.ironic.template.ironicInspector.inspectionNetwork
          - spec.ironic.template.ironicInspector.networkAttachments.0
          - spec.ovn.template.ovnController.nicMappings.ironic
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.ironic.ironicConductors.0.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.ironic.template.ironicConductors.0.customServiceConfig
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.ironic.ironicInspector.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.ironic.template.ironicInspector.customServiceConfig
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.nova.cellTemplates
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.nova.template.cellTemplates
        options:
          create: true
