---
# local-config: referenced, but not emitted by kustomize
apiVersion: v1
kind: ConfigMap
metadata:
  name: network-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  # nodes
  node_0:
    name: master-0
    internalapi_ip: 172.17.0.5
    tenant_ip: 172.19.0.5
    ctlplane_ip: 192.168.122.10
    storage_ip: 172.18.0.5
    bgp_ip:
      - 100.64.0.10
      - 100.65.0.10
    bgp_peers:
      - 100.64.0.9
      - 100.65.0.9
    loopback_ip: 99.99.0.3
    loopback_ipv6: f00d:f00d:f00d:f00d:f00d:f00d:f00d:13
    routes:
      config:
        - destination: 99.99.0.0/16
          next-hop-address: 100.64.0.9
          next-hop-interface: enp7s0
        - destination: 99.99.0.0/16
          next-hop-address: 100.65.0.9
          next-hop-interface: enp8s0
  node_1:
    name: master-1
    internalapi_ip: 172.17.0.6
    tenant_ip: 172.19.0.6
    ctlplane_ip: 192.168.122.11
    storage_ip: 172.18.0.6
    bgp_ip:
      - 100.64.1.10
      - 100.65.1.10
    bgp_peers:
      - 100.64.1.9
      - 100.65.1.9
    loopback_ip: 99.99.1.3
    loopback_ipv6: f00d:f00d:f00d:f00d:f00d:f00d:f00d:23
    routes:
      config:
        - destination: 99.99.0.0/16
          next-hop-address: 100.64.1.9
          next-hop-interface: enp7s0
        - destination: 99.99.0.0/16
          next-hop-address: 100.65.1.9
          next-hop-interface: enp8s0
  node_2:
    name: master-2
    internalapi_ip: 172.17.0.7
    tenant_ip: 172.19.0.7
    ctlplane_ip: 192.168.122.12
    storage_ip: 172.18.0.7
    bgp_ip:
      - 100.64.2.10
      - 100.65.2.10
    bgp_peers:
      - 100.64.2.9
      - 100.65.2.9
    loopback_ip: 99.99.2.3
    loopback_ipv6: f00d:f00d:f00d:f00d:f00d:f00d:f00d:33
    routes:
      config:
        - destination: 99.99.0.0/16
          next-hop-address: 100.64.2.9
          next-hop-interface: enp7s0
        - destination: 99.99.0.0/16
          next-hop-address: 100.65.2.9
          next-hop-interface: enp8s0
  node_3:
    name: worker-0
    internalapi_ip: 172.17.0.8
    tenant_ip: 172.19.0.8
    ctlplane_ip: 192.168.122.13
    storage_ip: 172.18.0.8
    bgp_ip:
      - 100.64.0.14
      - 100.65.0.14
    bgp_peers:
      - 100.64.0.13
      - 100.65.0.13
    loopback_ip: 99.99.0.4
    loopback_ipv6: f00d:f00d:f00d:f00d:f00d:f00d:f00d:14
    routes:
      config:
        - destination: 99.99.0.0/16
          next-hop-address: 100.64.0.13
          next-hop-interface: enp7s0
        - destination: 99.99.0.0/16
          next-hop-address: 100.65.0.13
          next-hop-interface: enp8s0
  node_4:
    name: worker-1
    internalapi_ip: 172.17.0.9
    tenant_ip: 172.19.0.9
    ctlplane_ip: 192.168.122.14
    storage_ip: 172.18.0.9
    bgp_ip:
      - 100.64.1.14
      - 100.65.1.14
    bgp_peers:
      - 100.64.1.13
      - 100.65.1.13
    loopback_ip: 99.99.1.4
    loopback_ipv6: f00d:f00d:f00d:f00d:f00d:f00d:f00d:24
    routes:
      config:
        - destination: 99.99.0.0/16
          next-hop-address: 100.64.1.13
          next-hop-interface: enp7s0
        - destination: 99.99.0.0/16
          next-hop-address: 100.65.1.13
          next-hop-interface: enp8s0
  node_5:
    name: worker-2
    internalapi_ip: 172.17.0.10
    tenant_ip: 172.19.0.10
    ctlplane_ip: 192.168.122.15
    storage_ip: 172.18.0.10
    bgp_ip:
      - 100.64.2.14
      - 100.65.2.14
    bgp_peers:
      - 100.64.2.13
      - 100.65.2.13
    loopback_ip: 99.99.2.4
    loopback_ipv6: f00d:f00d:f00d:f00d:f00d:f00d:f00d:34
    routes:
      config:
        - destination: 99.99.0.0/16
          next-hop-address: 100.64.2.13
          next-hop-interface: enp7s0
        - destination: 99.99.0.0/16
          next-hop-address: 100.65.2.13
          next-hop-interface: enp8s0
  node_6:
    name: worker-3
    internalapi_ip: 172.17.0.11
    tenant_ip: 172.19.0.11
    ctlplane_ip: 192.168.122.16
    storage_ip: 172.18.0.11
    bgp_ip:
      - 100.64.10.2
    bgp_peers:
      - 100.64.10.1
    loopback_ip: 99.99.10.2
    loopback_ipv6: f00d:f00d:f00d:f00d:f00d:f00d:f00d:43
    base_if: enp6s0
    routes:
      config:
        - destination: 192.168.133.0/24
          next-hop-address: 100.64.10.1
          next-hop-interface: enp7s0

  # networks
  ctlplane:
    dnsDomain: ctlplane.example.com
    subnets:
      - allocationRanges:
          - end: 192.168.122.120
            start: 192.168.122.100
          - end: 192.168.122.200
            start: 192.168.122.150
        cidr: 192.168.122.0/24
        gateway: 192.168.122.1
        name: subnet1
        routes:
          - destination: 192.168.123.0/24
            nexthop: 192.168.122.1
          - destination: 192.168.124.0/24
            nexthop: 192.168.122.1
      - allocationRanges:
          - end: 192.168.123.120
            start: 192.168.123.100
          - end: 192.168.123.170
            start: 192.168.123.150
        cidr: 192.168.123.0/24
        gateway: 192.168.123.1
        name: subnet2
        routes:
          - destination: 192.168.122.0/24
            nexthop: 192.168.123.1
          - destination: 192.168.124.0/24
            nexthop: 192.168.123.1ØØ
      - allocationRanges:
          - end: 192.168.124.120
            start: 192.168.124.100
          - end: 192.168.124.170
            start: 192.168.124.150
        cidr: 192.168.124.0/24
        gateway: 192.168.124.1
        name: subnet3
        routes:
          - destination: 192.168.122.0/24
            nexthop: 192.168.124.1
          - destination: 192.168.123.0/24
            nexthop: 192.168.124.1
    prefix-length: 24
    iface: enp6s0
    mtu: 1500
    lb_addresses:
      - 192.168.125.80-192.168.125.90
    endpoint_annotations:
      metallb.universe.tf/address-pool: ctlplane
      metallb.universe.tf/allow-shared-ip: ctlplane
      metallb.universe.tf/loadBalancerIPs: 192.168.125.80
    net-attach-def: |
      {
        "cniVersion": "0.3.1",
        "name": "ctlplane",
        "type": "bridge",
        "bridge": "ctlplane",
        "isDefaultGateway": true,
        "forceAddress": false,
        "ipMasq": true,
        "hairpinMode": true,
        "ipam": {
          "type": "whereabouts",
          "range": "192.168.125.0/24",
          "range_start": "192.168.125.30",
          "range_end": "192.168.125.70"
        }
      }

    ctlplaner1:
      dnsDomain: ctlplaner1.example.com
      endpoint_annotations:
        metallb.universe.tf/address-pool: ctlplaner1
        metallb.universe.tf/allow-shared-ip: ctlplaner1
        metallb.universe.tf/loadBalancerIPs: 192.168.123.80
      iface: eth1
      lb_addresses:
        - 192.168.123.80-192.168.123.90
      mtu: 1500
      net-attach-def: |
        {
          "cniVersion": "0.3.1",
          "name": "ctlplaner1",
          "type": "macvlan",
          "master": "eth1",
          "ipam": {
            "type": "whereabouts",
            "range": "192.168.123.0/24",
            "range_start": "192.168.123.30",
            "range_end": "192.168.123.70"
          }
        }
      prefix-length: 24
      subnets:
        - allocationRanges:
            - end: 192.168.123.120
              start: 192.168.123.100
            - end: 192.168.123.170
              start: 192.168.123.150
          cidr: 192.168.123.0/24
          gateway: 192.168.123.1
          name: subnet1
    ctlplaner2:
      dnsDomain: ctlplaner2.example.com
      endpoint_annotations:
        metallb.universe.tf/address-pool: ctlplaner2
        metallb.universe.tf/allow-shared-ip: ctlplaner2
        metallb.universe.tf/loadBalancerIPs: 192.168.124.80
      iface: eth1
      lb_addresses:
        - 192.168.124.80-192.168.124.90
      mtu: 1500
      net-attach-def: |
        {
          "cniVersion": "0.3.1",
          "name": "ctlplaner2",
          "type": "macvlan",
          "master": "eth1",
          "ipam": {
            "type": "whereabouts",
            "range": "192.168.124.0/24",
            "range_start": "192.168.124.30",
            "range_end": "192.168.124.70"
          }
        }
      prefix-length: 24
      subnets:
        - allocationRanges:
            - end: 192.168.124.120
              start: 192.168.124.100
            - end: 192.168.124.170
              start: 192.168.124.150
          cidr: 192.168.124.0/24
          gateway: 192.168.124.1
          name: subnet1

  internalapi:
    dnsDomain: internalapi.example.com
    subnets:
      - allocationRanges:
          - end: 172.17.0.250
            start: 172.17.0.100
        cidr: 172.17.0.0/24
        name: subnet1
        vlan: 20
    mtu: 1500
    prefix-length: 24
    iface: internalapi
    vlan: 20
    base_iface: enp6s0
    lb_addresses:
      - 172.17.0.80-172.17.0.90
    endpoint_annotations:
      metallb.universe.tf/address-pool: internalapi
      metallb.universe.tf/allow-shared-ip: internalapi
      metallb.universe.tf/loadBalancerIPs: 172.17.0.80
    net-attach-def: |
      {
        "cniVersion": "0.3.1",
        "name": "internalapi",
        "type": "bridge",
        "bridge": "internalapi",
        "isDefaultGateway": true,
        "forceAddress": false,
        "ipMasq": true,
        "hairpinMode": true,
        "ipam": {
          "type": "whereabouts",
          "range": "172.17.0.0/24",
          "range_start": "172.17.0.30",
          "range_end": "172.17.0.70"
        }
      }
  storage:
    dnsDomain: storage.example.com
    subnets:
      - allocationRanges:
          - end: 172.18.0.250
            start: 172.18.0.100
        cidr: 172.18.0.0/24
        name: subnet1
        vlan: 21
    mtu: 1500
    prefix-length: 24
    iface: storage
    vlan: 21
    base_iface: enp6s0
    lb_addresses:
      - 172.18.0.80-172.18.0.90
    net-attach-def: |
      {
        "cniVersion": "0.3.1",
        "name": "storage",
        "type": "bridge",
        "bridge": "storage",
        "isDefaultGateway": true,
        "forceAddress": false,
        "ipMasq": true,
        "hairpinMode": true,
        "ipam": {
          "type": "whereabouts",
          "range": "172.18.0.0/24",
          "range_start": "172.18.0.30",
          "range_end": "172.18.0.70"
        }
      }
  tenant:
    dnsDomain: tenant.example.com
    subnets:
      - allocationRanges:
          - end: 172.19.0.250
            start: 172.19.0.100
        cidr: 172.19.0.0/24
        name: subnet1
        vlan: 22
    mtu: 1500
    prefix-length: 24
    iface: tenant
    vlan: 22
    base_iface: enp6s0
    lb_addresses:
      - 172.19.0.80-172.19.0.90
    net-attach-def: |
      {
        "cniVersion": "0.3.1",
        "name": "tenant",
        "type": "bridge",
        "bridge": "tenant",
        "isDefaultGateway": true,
        "forceAddress": false,
        "ipMasq": true,
        "hairpinMode": true,
        "ipam": {
          "type": "whereabouts",
          "range": "172.19.0.0/24",
          "range_start": "172.19.0.30",
          "range_end": "172.19.0.70"
        }
      }
  octavia:
    dnsDomain: octavia.openstack.lab
    mtu: 1500
    vlan: 23
    base_iface: enp6s0
    net-attach-def: |
      {
        "cniVersion": "0.3.1",
        "name": "octavia",
        "type": "bridge",
        "bridge": "octbr",
        "ipam": {
          "type": "whereabouts",
          "range": "172.23.0.0/24",
          "range_start": "172.23.0.30",
          "range_end": "172.23.0.70",
          "routes": [
            {
              "dst": "172.24.0.0/16",
              "gw": "172.23.0.150"
            }
          ]
        }
      }
  external:
    dnsDomain: external.example.com
    subnets:
      - allocationRanges:
          - end: 10.0.0.250
            start: 10.0.0.100
        cidr: 10.0.0.0/24
        gateway: 10.0.0.1
        name: subnet1
    mtu: 1500

  bgp:
    prefix-length: 30
    prefix-length-worker-3: 24
    ifaces:
      - enp7s0
      - enp8s0
    asn: 64999
    peer_asn: 64999
    subnets:
      bgpnet0:
        - name: subnet0
          allocationRanges:
            - end: 100.64.0.6
              start: 100.64.0.1
          cidr: 100.64.0.0/29
          gateway: 100.64.0.1
          routes:
            - destination: 0.0.0.0/0
              nexthop: 100.64.0.1
        - name: subnet1
          allocationRanges:
            - end: 100.64.1.6
              start: 100.64.1.1
          cidr: 100.64.1.0/29
          gateway: 100.64.1.1
          routes:
            - destination: 0.0.0.0/0
              nexthop: 100.64.1.1
        - name: subnet2
          allocationRanges:
            - end: 100.64.2.6
              start: 100.64.2.1
          cidr: 100.64.2.0/29
          gateway: 100.64.2.1
          routes:
            - destination: 0.0.0.0/0
              nexthop: 100.64.2.1
      bgpnet1:
        - name: subnet0
          allocationRanges:
            - end: 100.65.0.6
              start: 100.65.0.1
          cidr: 100.65.0.0/29
          gateway: 100.65.0.1
          routes:
            - destination: 0.0.0.0/0
              nexthop: 100.65.0.1
        - name: subnet1
          allocationRanges:
            - end: 100.65.1.6
              start: 100.65.1.1
          cidr: 100.65.1.0/29
          gateway: 100.65.1.1
          routes:
            - destination: 0.0.0.0/0
              nexthop: 100.65.1.1
        - name: subnet2
          allocationRanges:
            - end: 100.65.2.6
              start: 100.65.2.1
          cidr: 100.65.2.0/29
          gateway: 100.65.2.1
          routes:
            - destination: 0.0.0.0/0
              nexthop: 100.65.2.1
      bgpmainnet:
        - name: subnet0
          cidr: 99.99.0.0/28
          allocationRanges:
            - end: 99.99.0.14
              start: 99.99.0.2
        - name: subnet1
          cidr: 99.99.1.0/28
          allocationRanges:
            - end: 99.99.1.14
              start: 99.99.1.2
        - name: subnet2
          cidr: 99.99.2.0/28
          allocationRanges:
            - end: 99.99.2.14
              start: 99.99.2.2
        - name: subnet10
          cidr: 99.99.10.0/28
          allocationRanges:
            - end: 99.99.10.14
              start: 99.99.10.2
      bgpmainnetv6:
        - name: subnet0
          cidr: f00d:f00d:f00d:f00d:f00d:f00d:f00d:0010/124
          allocationRanges:
            - end: f00d:f00d:f00d:f00d:f00d:f00d:f00d:001e
              start: f00d:f00d:f00d:f00d:f00d:f00d:f00d:0012
        - name: subnet1
          cidr: f00d:f00d:f00d:f00d:f00d:f00d:f00d:0020/124
          allocationRanges:
            - end: f00d:f00d:f00d:f00d:f00d:f00d:f00d:002e
              start: f00d:f00d:f00d:f00d:f00d:f00d:f00d:0022
        - name: subnet2
          cidr: f00d:f00d:f00d:f00d:f00d:f00d:f00d:0030/124
          allocationRanges:
            - end: f00d:f00d:f00d:f00d:f00d:f00d:f00d:003e
              start: f00d:f00d:f00d:f00d:f00d:f00d:f00d:0032
        - name: subnet3
          cidr: f00d:f00d:f00d:f00d:f00d:f00d:f00d:0040/124
          allocationRanges:
            - end: f00d:f00d:f00d:f00d:f00d:f00d:f00d:004e
              start: f00d:f00d:f00d:f00d:f00d:f00d:f00d:0042
    bgpdefs:
      node0:
        bgpnet0:
          bgp_peer: 100.64.0.9
          bgp_ip: 100.64.0.10
        bgpnet1:
          bgp_peer: 100.65.0.9
          bgp_ip: 100.65.0.10
        routes:
          config:
            - destination: 99.99.0.0/16
              next-hop-address: 100.64.0.9
              next-hop-interface: enp7s0
            - destination: 99.99.0.0/16
              next-hop-address: 100.65.0.9
              next-hop-interface: enp8s0
      node1:
        bgpnet0:
          bgp_peer: 100.64.1.9
          bgp_ip: 100.64.1.10
        bgpnet1:
          bgp_peer: 100.65.1.9
          bgp_ip: 100.65.1.10
        routes:
          config:
            - destination: 99.99.0.0/16
              next-hop-address: 100.64.1.9
              next-hop-interface: enp7s0
            - destination: 99.99.0.0/16
              next-hop-address: 100.65.1.9
              next-hop-interface: enp8s0
      node2:
        bgpnet0:
          bgp_peer: 100.64.2.9
          bgp_ip: 100.64.2.10
        bgpnet1:
          bgp_peer: 100.65.2.9
          bgp_ip: 100.65.2.10
        routes:
          config:
            - destination: 99.99.0.0/16
              next-hop-address: 100.64.2.9
              next-hop-interface: enp7s0
            - destination: 99.99.0.0/16
              next-hop-address: 100.65.2.9
              next-hop-interface: enp8s0
      node3:
        bgpnet0:
          bgp_peer: 100.64.0.13
          bgp_ip: 100.64.0.14
        bgpnet1:
          bgp_peer: 100.65.0.13
          bgp_ip: 100.65.0.14
        routes:
          config:
            - destination: 99.99.0.0/16
              next-hop-address: 100.64.0.13
              next-hop-interface: enp7s0
            - destination: 99.99.0.0/16
              next-hop-address: 100.65.0.13
              next-hop-interface: enp8s0
      node4:
        bgpnet0:
          bgp_peer: 100.64.1.13
          bgp_ip: 100.64.1.14
        bgpnet1:
          bgp_peer: 100.65.1.13
          bgp_ip: 100.65.1.14
        routes:
          config:
            - destination: 99.99.0.0/16
              next-hop-address: 100.64.1.13
              next-hop-interface: enp7s0
            - destination: 99.99.0.0/16
              next-hop-address: 100.65.1.13
              next-hop-interface: enp8s0
      node5:
        bgpnet0:
          bgp_peer: 100.64.2.13
          bgp_ip: 100.64.2.14
        bgpnet1:
          bgp_peer: 100.65.2.13
          bgp_ip: 100.65.2.14
        routes:
          config:
            - destination: 99.99.0.0/16
              next-hop-address: 100.64.2.13
              next-hop-interface: enp7s0
            - destination: 99.99.0.0/16
              next-hop-address: 100.65.2.13
              next-hop-interface: enp8s0
      node6:
        bgpnet0:
          bgp_peer: 100.64.10.1
          bgp_ip: 100.64.10.2
        routes:
          config:
            - destination: 192.168.133.0/24
              next-hop-address: 100.64.10.1
              next-hop-interface: enp7s0
    net-attach-def:
      node6: |
        {
          "cniVersion": "0.3.1",
          "name": "bgpnet-worker-3",
          "type": "macvlan",
          "master": "enp7s0",
          "ipam": {
            "type": "whereabouts",
            "range": "100.64.10.0/24",
            "range_start": "100.64.10.10",
            "range_end": "100.64.10.19",
            "routes": [{
              "dst": "192.168.133.0/24",
              "gw": "100.64.10.1"
            }]
          }
        }

  loopback:
    prefix-length: 32
    prefix-length-ipv6: 128
    iface: lo
  datacentre:
    net-attach-def: |
      {
        "cniVersion": "0.3.1",
        "name": "datacentre",
        "type": "bridge",
        "bridge": "ospbr",
        "ipam": {}
      }

  dns-resolver:
    config:
      server:
        - 192.168.122.1
      search: []
    options:
      - key: server
        values:
          - 192.168.122.1

  routes:
    config: []

  rabbitmq:
    endpoint_annotations:
      metallb.universe.tf/address-pool: internalapi
      metallb.universe.tf/loadBalancerIPs: 172.17.0.85
  rabbitmq-cell1:
    endpoint_annotations:
      metallb.universe.tf/address-pool: internalapi
      metallb.universe.tf/loadBalancerIPs: 172.17.0.86

  lbServiceType: LoadBalancer
  storageClass: local-storage
  bridgeName: ospbr
