apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
# Set namespace to OpenStack on all namespaced objects without a namespace
- |-
  apiVersion: builtin
  kind: NamespaceTransformer
  metadata:
    name: _ignored_
    namespace: openstack
  setRoleBindingSubjects: none
  unsetOnly: true
  fieldSpecs:
  - path: metadata/name
    kind: Namespace
    create: true

components:
- ../../../lib/networking
- ../../../lib/control-plane

replacements:
# Neutron control plane OvS DPDK customization
- source:
    kind: ConfigMap
    name: service-values
    fieldPath: data.neutron.customServiceConfig
  targets:
  - select:
      kind: OpenStackControlPlane
    fieldPaths:
    - spec.neutron.template.customServiceConfig
    options:
      create: true
# OVN control plane OvS DPDK customization
- source:
    kind: ConfigMap
    name: service-values
    fieldPath: data.ovn.ovnController
  targets:
  - select:
      kind: OpenStackControlPlane
    fieldPaths:
    - spec.ovn.template.ovnController
    options:
      create: true
