---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
      - path: metadata/name
        kind: Namespace
        create: true

components:
  - ../../../lib/networking/metallb
  - ../../../lib/networking/netconfig
  - ../../../lib/networking/nad
  - metallb

resources:
  - nad.yaml

patches:
  - target:
      version: v1beta1
      kind: NetConfig
      name: netconfig
    patch: |-
      - op: add
        path: /spec/networks/-
        value:
          dnsDomain: _replaced_
          name: storagemgmt
          subnets:
            - _replaced_
          mtu: 1500
      - op: add
        path: /spec/networks/-
        value:
          dnsDomain: _replaced_
          name: designate
          subnets:
            - _replaced_
          mtu: 1500
      - op: add
        path: /spec/networks/-
        value:
          dnsDomain: _replaced_
          name: designateext
          subnets:
            - _replaced_
          mtu: 1500
      - op: add
        path: /spec/networks/-
        value:
          dnsDomain: _replaced_
          name: octavia
          mtu: 1500

replacements:
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.storagemgmt.dnsDomain
    targets:
      - select:
          kind: NetConfig
        fieldPaths:
          - spec.networks.[name=storagemgmt].dnsDomain

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.storagemgmt.mtu
    targets:
      - select:
          kind: NetConfig
        fieldPaths:
          - spec.networks.[name=storagemgmt].mtu

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.storagemgmt.subnets
    targets:
      - select:
          kind: NetConfig
        fieldPaths:
          - spec.networks.[name=storagemgmt].subnets

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.designate.dnsDomain
    targets:
      - select:
          kind: NetConfig
        fieldPaths:
          - spec.networks.[name=designate].dnsDomain

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.designate.mtu
    targets:
      - select:
          kind: NetConfig
        fieldPaths:
          - spec.networks.[name=designate].mtu

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.designate.subnets
    targets:
      - select:
          kind: NetConfig
        fieldPaths:
          - spec.networks.[name=designate].subnets

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.designateext.dnsDomain
    targets:
      - select:
          kind: NetConfig
        fieldPaths:
          - spec.networks.[name=designateext].dnsDomain

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.designateext.mtu
    targets:
      - select:
          kind: NetConfig
        fieldPaths:
          - spec.networks.[name=designateext].mtu

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.designateext.subnets
    targets:
      - select:
          kind: NetConfig
        fieldPaths:
          - spec.networks.[name=designateext].subnets

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.designate.net-attach-def
    targets:
      - select:
          kind: NetworkAttachmentDefinition
          name: designate
        fieldPaths:
          - spec.config

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.designateext.net-attach-def
    targets:
      - select:
          kind: NetworkAttachmentDefinition
          name: designateext
        fieldPaths:
          - spec.config

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.octavia.dnsDomain
    targets:
      - select:
          kind: NetConfig
        fieldPaths:
          - spec.networks.[name=octavia].dnsDomain

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.octavia.mtu
    targets:
      - select:
          kind: NetConfig
        fieldPaths:
          - spec.networks.[name=octavia].mtu

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.octavia.net-attach-def
    targets:
      - select:
          kind: NetworkAttachmentDefinition
          name: octavia
        fieldPaths:
          - spec.config
