---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-extra-config
  namespace: openstack2
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  25-nova-extra.conf: |
    [keystone_authtoken]
    region_name = regionTwo
    [placement]
    region_name = regionTwo
    [glance]
    region_name = regionTwo
    [neutron]
    region_name = regionTwo
    [cinder]
    os_region_name = regionTwo
    [barbican]
    region_name = regionTwo
    [oslo_limit]
    endpoint_region_name = regionTwo
