---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  - |-
      apiVersion: builtin
      kind: NamespaceTransformer
      metadata:
        name: _ignored_
        namespace: openstack
      setRoleBindingSubjects: none
      unsetOnly: true
      fieldSpecs:
        - path: metadata/name
          kind: Namespace
          create: true

components:
  - ../../lib/control-plane

replacements:
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.telemetry.enabled
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.telemetry.enabled
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.telemetry.metricStorage.enabled
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.telemetry.template.metricStorage.enabled
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.telemetry.autoscaling.enabled
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.telemetry.template.autoscaling.enabled
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.telemetry.ceilometer.enabled
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.telemetry.template.ceilometer.enabled
        options:
          create: true
