---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - dns.yaml

replacements:
  - source:
      kind: ConfigMap
      name: dns-values
      fieldPath: data.servers
    targets:
      - select:
          kind: DNS
          name: default
        fieldPaths:
          - spec.servers
        options:
          create: true
