---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../va/hci/
  # - https://github.com/openstack-k8s-operators/architecture/va/hci?ref=main
  ## It's possible to replace ../../../../va/hci/ with a git checkout URL as per:
  ## https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md

resources:
  - nncp/values.yaml
  - service-values.yaml
