---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  # Set namespace to OpenStack on all namespaced objects without a namespace
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
    - path: metadata/name
      kind: Namespace
      create: true

secretGenerator:
  - name: baremetalset-password-secret
    behavior: create
    literals:
      - NodeRootPassword=redhat
    options:
      disableNameSuffixHash: true

components:
  - ../../../../../lib/dataplane/nodeset

resources:
  - network-data-secrets.yaml
  - nova_gpu.yaml

replacements:
  # Nova compute CPU pinning customization
  - source:
      kind: ConfigMap
      name: edpm-nodeset-values
      fieldPath: data.nova.compute.conf
    targets:
      - select:
          kind: ConfigMap
          name: cpu-pinning-nova
        fieldPaths:
          - data.25-cpu-pinning-nova\.conf
        options:
          create: true
  # Nova compute PCI passthrough customization
  - source:
      kind: ConfigMap
      name: edpm-nodeset-values
      fieldPath: data.nova.pci.conf
    targets:
      - select:
          kind: ConfigMap
          name: gpu-nova
        fieldPaths:
          - data.03-gpu-nova\.conf
        options:
          create: true
  - source:
      kind: ConfigMap
      name: edpm-nodeset-values
      fieldPath: data.preProvisioned
    targets:
      - select:
          kind: OpenStackDataPlaneNodeSet
          name: openstack-edpm
        fieldPaths:
          - spec.preProvisioned
        options:
          create: true
  - source:
      kind: ConfigMap
      name: edpm-nodeset-values
      fieldPath: data.baremetalSetTemplate
    targets:
      - select:
          kind: OpenStackDataPlaneNodeSet
          name: openstack-edpm
        fieldPaths:
          - spec.baremetalSetTemplate
        options:
          create: true
  # BMO root password for provisioned host
  - source:
      kind: ConfigMap
      name: edpm-nodeset-values
      fieldPath: data.root_password
    targets:
      - select:
          kind: Secret
          name: baremetalset-password-secret
        fieldPaths:
          - data.NodeRootPassword
        options:
          create: true
  # BMO networkData for provisioned host
  - source:
      kind: ConfigMap
      name: edpm-nodeset-values
      fieldPath: data.baremetalHostsNetworkData.edpm-compute-0
    targets:
      - select:
          kind: Secret
          name: edpm-compute-0-network-data
        fieldPaths:
          - stringData
        options:
          create: true
