---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  # --- Fields required by lib/control-plane ---
  preserveJobs: false
  tls:
    caBundleSecretName: ""

  # --- Below are VA/DT-specific data ---
  glance:
    customServiceConfig: |
      [DEFAULT]
      enabled_backends = default_backend:swift
      [glance_store]
      default_backend = default_backend
      [default_backend]
      swift_store_create_container_on_put = True
      swift_store_auth_version = 3
      swift_store_auth_address = {{ .KeystoneInternalURL }}
      swift_store_endpoint_type = internalURL
      swift_store_user = service:glance
      swift_store_key = {{ .ServicePassword }}
    default:
      replicas: 1

  swift:
    enabled: true

  octavia:
    enabled: true
    amphoraImageContainerImage: quay.io/gthiemonge/octavia-amphora-image
    apacheContainerImage: registry.redhat.io/ubi9/httpd-24:latest
    octaviaAPI:
      networkAttachments:
        - internalapi
      customServiceConfig: |
        [controller_worker]
        loadbalancer_topology=ACTIVE_STANDBY
    octaviaHousekeeping:
      networkAttachments:
        - octavia
      customServiceConfig: |
        [controller_worker]
        loadbalancer_topology=ACTIVE_STANDBY
    octaviaHealthManager:
      networkAttachments:
        - octavia
      customServiceConfig: |
        [controller_worker]
        loadbalancer_topology=ACTIVE_STANDBY
    octaviaWorker:
      networkAttachments:
        - octavia
      customServiceConfig: |
        [controller_worker]
        loadbalancer_topology=ACTIVE_STANDBY
    nodeSelector:
      node-role.kubernetes.io/worker: ""

  neutron:
    customServiceConfig: |
      [DEFAULT]
      vlan_transparent = true
      debug = true
      dns_domain = example.org.
      external_dns_driver = designate
      [ovs]
      igmp_snooping_enable = true
      [designate]
      url = https://designate-internal.openstack.svc:9001/v2
      auth_type = password
      auth_url = {{ .KeystoneInternalURL }}
      username = {{ .ServiceUser }}
      password = {{ .ServicePassword }}
      project_name = service
      project_domain_name = Default
      user_domain_name = Default
      allow_reverse_dns_lookup = True
      ipv4_ptr_zone_prefix_size = 24
      ipv6_ptr_zone_prefix_size = 116
      ptr_zone_email = admin@example.org

  designate-redis:
    enabled: true
    replicas: 1

  designate:
    enabled: true
    nsRecords:
      - hostname: ns1.example.org.
        priority: 1
      - hostname: ns2.example.org.
        priority: 2
    bind9Services:
      services:
        - metadata:
            annotations:
              metallb.universe.tf/address-pool: designateext
              metallb.universe.tf/allow-shared-ip: designateext
              metallb.universe.tf/LoadBalancerIPs: 172.34.0.80
          spec:
            type: LoadBalancer
        - metadata:
            annotations:
              metallb.universe.tf/address-pool: designateext
              metallb.universe.tf/allow-shared-ip: designateext
              metallb.universe.tf/LoadBalancerIPs: 172.34.0.81
          spec:
            type: LoadBalancer
        - metadata:
            annotations:
              metallb.universe.tf/address-pool: designateext
              metallb.universe.tf/allow-shared-ip: designateext
              metallb.universe.tf/LoadBalancerIPs: 172.34.0.82
          spec:
            type: LoadBalancer
