# This is the kustomization for the FINAL step, edpm-post-ceph
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../dt/dcn/edpm-post-ceph/nodeset

resources:
  - control-plane/networking/nncp/values.yaml
  - edpm-pre-ceph/nodeset/values.yaml
  - service-values.yaml
  - values.yaml
