---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../../../dt/bgp/edpm/nodeset
  ## It's possible to replace ../../../../../../dt/bgp/edpm/nodeset with a git checkout URL as per:
  ## https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md

resources:
  - values.yaml

patches:
  - target:
      kind: OpenStackDataPlaneNodeSet
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: r1-networker-nodes

  - target:
      kind: Secret
      name: nova-migration-ssh-key
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          config.kubernetes.io/local-config: true
