apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
# Set namespace to OpenStack on all namespaced objects without a namespace
- |-
  apiVersion: builtin
  kind: NamespaceTransformer
  metadata:
    name: _ignored_
    namespace: openstack
  setRoleBindingSubjects: none
  unsetOnly: true
  fieldSpecs:
  - path: metadata/name
    kind: Namespace
    create: true

components:
- ../../../lib/control-plane
- ../../../lib/dataplane

resources:
- ceph_secret.yaml
- nova_ceph.yaml

patches:
- target:
    kind: OpenStackDataPlaneDeployment
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: edpm-deployment-post-ceph
- target:
    kind: OpenStackDataPlaneNodeSet
    name: .*
  path: extra_mounts.yaml

replacements:
# Control plane custom service configs
- source:
    kind: ConfigMap
    name: service-values
    fieldPath: data.cinderBackup.customServiceConfig
  targets:
    - select:
        kind: OpenStackControlPlane
      fieldPaths:
        - spec.cinder.template.cinderBackup.customServiceConfig
      options:
        create: true
- source:
    kind: ConfigMap
    name: service-values
    fieldPath: data.cinderVolumes.ceph
  targets:
    - select:
        kind: OpenStackControlPlane
      fieldPaths:
        - spec.cinder.template.cinderVolumes.ceph
      options:
        create: true
- source:
    kind: ConfigMap
    name: service-values
    fieldPath: data.glance.customServiceConfig
  targets:
    - select:
        kind: OpenStackControlPlane
      fieldPaths:
        - spec.glance.template.customServiceConfig
      options:
        create: true
- source:
    kind: ConfigMap
    name: service-values
    fieldPath: data.manila.enabled
  targets:
    - select:
        kind: OpenStackControlPlane
      fieldPaths:
        - spec.manila.enabled
      options:
        create: true
- source:
    kind: ConfigMap
    name: service-values
    fieldPath: data.manilaShares.customServiceConfig
  targets:
    - select:
        kind: OpenStackControlPlane
      fieldPaths:
        - spec.manila.template.manilaShares.customServiceConfig
      options:
        create: true
- source:
    kind: ConfigMap
    name: service-values
    fieldPath: data.extraMounts
  targets:
    - select:
        kind: OpenStackControlPlane
      fieldPaths:
        - spec.extraMounts
      options:
        create: true
# Ceph keyring
- source:
    kind: ConfigMap
    name: edpm-values
    fieldPath: data.ceph.keyring
  targets:
  - select:
      kind: Secret
      name: ceph-conf-files
    fieldPaths:
    - data.ceph\.client\.openstack\.keyring
    options:
      create: true
# Ceph conf
- source:
    kind: ConfigMap
    name: edpm-values
    fieldPath: data.ceph.conf
  targets:
  - select:
      kind: Secret
      name: ceph-conf-files
    fieldPaths:
    - data.ceph\.conf
    options:
      create: true
# Nova Ceph conf
- source:
    kind: ConfigMap
    name: edpm-values
    fieldPath: data.nova.ceph.conf
  targets:
  - select:
      kind: ConfigMap
      name: ceph-nova
    fieldPaths:
    - data.03-ceph-nova\.conf
    options:
      create: true
