apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
# Set namespace to OpenStack on all namespaced objects without a namespace
- |-
  apiVersion: builtin
  kind: NamespaceTransformer
  metadata:
    name: _ignored_
    namespace: openstack
  setRoleBindingSubjects: none
  unsetOnly: true
  fieldSpecs:
  - path: metadata/name
    kind: Namespace
    create: true

components:
- ../../examples/dt/bgp/config/lib/networking
- ../../examples/dt/bgp/config/lib/control-plane

replacements:
  # Control plane customization
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.glance.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.glance.template.customServiceConfig
        options:
          create: true
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.glance.default.replicas
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.glance.template.glanceAPIs.default.replicas
        options:
          create: true
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.swift.enabled
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.swift.enabled
        options:
          create: true

# Add StorageMgmt network template, as it is needed for CephHCI
# patches:
# - target:
#     version: v1beta1
#     kind: NetConfig
#     name: netconfig
#   patch: |-
#     - op: add
#       path: /spec/networks/-
#       value:
#         dnsDomain: _replaced_
#         name: StorageMgmt
#         subnets:
#           - _replaced_
#         mtu: 1500

# Add StorageMgmt network replacements
# replacements:
# # NetConfig dnsDomain specific to this VA
# - source:
#     kind: ConfigMap
#     name: network-values
#     fieldPath: data.storagemgmt.dnsDomain
#   targets:
#   - select:
#       kind: NetConfig
#     fieldPaths:
#     - spec.networks.[name=StorageMgmt].dnsDomain
# # NetConfig MTU specific to this VA
# - source:
#     kind: ConfigMap
#     name: network-values
#     fieldPath: data.storagemgmt.mtu
#   targets:
#   - select:
#       kind: NetConfig
#     fieldPaths:
#     - spec.networks.[name=StorageMgmt].mtu
# # NetConfig subnets specific to this VA
# - source:
#     kind: ConfigMap
#     name: network-values
#     fieldPath: data.storagemgmt.subnets
#   targets:
#   - select:
#       kind: NetConfig
#     fieldPaths:
#     - spec.networks.[name=StorageMgmt].subnets
