---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../dt/uni04delta-ipv6/edpm/nodeset

resources:
  - control-plane/networking/nncp/values.yaml
  - control-plane/service-values.yaml
  - values.yaml

replacements:
  # Glance
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.glance.glanceAPIs.default.customServiceConfigSecrets
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.glance.template.glanceAPIs.default.customServiceConfigSecrets
        options:
          create: true
