apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../../../va/nfv/ovs-dpdk/edpm/bmh
  # - https://github.com/openstack-k8s-operators/architecture/va/nfv/ovs-dpdk/edpm/bmh/?ref=main
  ## It's possible to replace ../../../../../va/nfv/ovs-dpdk/edpm/bmh with a git checkout URL as per:
  ## https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md

resources:
  - values.yaml
