resources:
- cert_manager_namespace.yaml
- cert_manager_operatorgroup.yaml
- cert_manager_subscription.yaml
- metallb_namespace.yaml
- metallb_operatorgroup.yaml
- metallb_subscription.yaml
- nmstate_namespace.yaml
- nmstate_operatorgroup.yaml
- nmstate_subscription.yaml
- openshift-local-storage.yaml
