---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../lib/networking/metallb
  - ../../../../lib/networking/netconfig
  - ../../../../lib/networking/nad
  - ../../../../dt/uni02beta

resources:
  - nncp/values.yaml
  - service-values.yaml
