---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
      - path: metadata/name
        kind: Namespace
        create: true

components:
  - ../../../lib/nncp

patches:
  - target:
      kind: NodeNetworkConfigurationPolicy
      name: master-0
    patch: |-
      - op: add
        path: /spec/desiredState/interfaces/-
        value:
          description: Octavia vlan host interface
          name: octavia
          state: up
          type: vlan
          vlan:
            base-iface: _replaced_
            id: _replaced_

  - target:
      kind: NodeNetworkConfigurationPolicy
      name: master-0
    patch: |-
      - op: add
        path: /spec/desiredState/interfaces/-
        value:
          description: Octavia bridge
          mtu: 1500
          name: octbr
          type: linux-bridge
          bridge:
            options:
              stp:
                enabled: false
            port:
              - name: octavia

  - target:
      kind: NodeNetworkConfigurationPolicy
      name: master-1
    patch: |-
      - op: add
        path: /spec/desiredState/interfaces/-
        value:
          description: Octavia vlan host interface
          name: octavia
          state: up
          type: vlan
          vlan:
            base-iface: _replaced_
            id: _replaced_

  - target:
      kind: NodeNetworkConfigurationPolicy
      name: master-1
    patch: |-
      - op: add
        path: /spec/desiredState/interfaces/-
        value:
          description: Octavia bridge
          mtu: 1500
          name: octbr
          type: linux-bridge
          bridge:
            options:
              stp:
                enabled: false
            port:
              - name: octavia

  - target:
      kind: NodeNetworkConfigurationPolicy
      name: master-2
    patch: |-
      - op: add
        path: /spec/desiredState/interfaces/-
        value:
          description: Octavia vlan host interface
          name: octavia
          state: up
          type: vlan
          vlan:
            base-iface: _replaced_
            id: _replaced_

  - target:
      kind: NodeNetworkConfigurationPolicy
      name: master-2
    patch: |-
      - op: add
        path: /spec/desiredState/interfaces/-
        value:
          description: Octavia bridge
          mtu: 1500
          name: octbr
          type: linux-bridge
          bridge:
            options:
              stp:
                enabled: false
            port:
              - name: octavia

replacements:
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.octavia.base_iface
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-0
        fieldPaths:
          - spec.desiredState.interfaces.[name=octavia].vlan.base-iface

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.octavia.vlan
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-0
        fieldPaths:
          - spec.desiredState.interfaces.[name=octavia].vlan.id

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.octavia.base_iface
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-1
        fieldPaths:
          - spec.desiredState.interfaces.[name=octavia].vlan.base-iface

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.octavia.vlan
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-1
        fieldPaths:
          - spec.desiredState.interfaces.[name=octavia].vlan.id

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.octavia.base_iface
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-2
        fieldPaths:
          - spec.desiredState.interfaces.[name=octavia].vlan.base-iface

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.octavia.vlan
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-2
        fieldPaths:
          - spec.desiredState.interfaces.[name=octavia].vlan.id
