# yamllint disable rule:line-length
# local-config: referenced, but not emitted by kustomize
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: edpm-nodeset-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  ssh_keys:
    # Authorized keys that will have access to the dataplane computes via SSH
    authorized: CHANGEME
    # The private key that will have access to the dataplane computes via SSH
    private: CHANGEME2
    # The public key that will have access to the dataplane computes via SSH
    public: CHANGEME3
  nodeset:
    ansible:
      ansibleUser: cloud-admin
      ansiblePort: 22
      ansibleVars:
        edpm_ovn_encap_ip: "{{ lookup('vars', 'bgpmainnetv6_ip') }}"
        edpm_ovn_bgp_agent_expose_tenant_networks: false
        edpm_frr_bgp_ipv4_src_network: bgpmainnet
        edpm_frr_bgp_ipv6_src_network: bgpmainnetv6
        edpm_frr_bgp_neighbor_password: f00barZ
        timesync_ntp_servers:
          - hostname: pool.ntp.org
        # conntrack is necessary for some tobiko tests
        edpm_bootstrap_command: |
          dnf -y install conntrack-tools
        edpm_network_config_hide_sensitive_logs: false
        edpm_network_config_os_net_config_mappings:
          edpm-r1-compute-0:
            nic2: 6a:fe:54:3f:8a:02  # CHANGEME
        edpm_network_config_template: |
          ---
          {% set mtu_list = [ctlplane_mtu] %}
          {% for network in nodeset_networks %}
          {% set _ = mtu_list.append(lookup('vars', networks_lower[network] ~ '_mtu')) %}
          {%- endfor %}
          {% set min_viable_mtu = mtu_list | max %}
          network_config:
          - type: ovs_bridge
            name: {{ neutron_physical_bridge_name }}
            use_dhcp: false
            use_dhcpv6: true  # needed to enable IPv6 on bridges
          - type: interface
            name: nic1
            use_dhcp: true
            defroute: false
          - type: interface
            name: nic2
            use_dhcp: false
            defroute: false
            dns_servers: {{ ctlplane_dns_nameservers }}
            domain: {{ dns_search_domains }}
            addresses:
              - ip_netmask: {{ ctlplane_ip }}/{{ ctlplane_cidr }}
            routes:
              - destination: "2620:cf:cf:aaaa::/64"
                nexthop: {{ ctlplane_gateway_ip }}
              - destination: "2620:cf:cf:aaac::/64"
                nexthop: {{ ctlplane_gateway_ip }}
              - destination: "2620:cf:cf:aaad::/64"
                nexthop: {{ ctlplane_gateway_ip }}
          - type: interface
            name: nic3
            use_dhcp: false
            addresses:
            - ip_netmask: {{ lookup('vars', 'bgpnet0_ip') }}/126
            - ip_netmask: {{ lookup('vars', 'bgpnet0ipv4_ip') }}/30
          - type: interface
            name: nic4
            use_dhcp: false
            addresses:
            - ip_netmask: {{ lookup('vars', 'bgpnet1_ip') }}/126
            - ip_netmask: {{ lookup('vars', 'bgpnet1ipv4_ip') }}/30
          - type: interface
            name: lo
            addresses:
            - ip_netmask: {{ lookup('vars', 'bgpmainnet_ip') }}/32
            - ip_netmask: {{ lookup('vars', 'bgpmainnetv6_ip') }}/128
            - ip_netmask: {{ lookup('vars', 'internalapi_ip') }}/128
            - ip_netmask: {{ lookup('vars', 'storage_ip') }}/128
            - ip_netmask: {{ lookup('vars', 'tenant_ip') }}/128
        edpm_sshd_allowed_ranges:
          - '2620:cf:cf:aaad::0/64'
        edpm_sshd_configure_firewall: true
        gather_facts: false
        neutron_physical_bridge_name: br-ex
        neutron_public_interface_name: eth1
    networks:
      - defaultRoute: true
        name: CtlPlane
        subnetName: subnet1
      - name: InternalApi
        subnetName: subnet1
      - name: Storage
        subnetName: subnet1
      - name: Tenant
        subnetName: subnet1
      - name: BgpNet0
        subnetName: subnet0
      - name: BgpNet1
        subnetName: subnet0
      - name: BgpNet0ipv4
        subnetName: subnet0
      - name: BgpNet1ipv4
        subnetName: subnet0
      - name: BgpMainNet
        subnetName: subnet0
      - name: BgpMainNetV6
        subnetName: subnet0
      - name: BgpNet0
        subnetName: subnet1
      - name: BgpNet1
        subnetName: subnet1
      - name: BgpNet0ipv4
        subnetName: subnet1
      - name: BgpNet1ipv4
        subnetName: subnet1
      - name: BgpMainNet
        subnetName: subnet1
      - name: BgpMainNetV6
        subnetName: subnet1
      - name: BgpNet0
        subnetName: subnet2
      - name: BgpNet1
        subnetName: subnet2
      - name: BgpNet0ipv4
        subnetName: subnet2
      - name: BgpNet1ipv4
        subnetName: subnet2
      - name: BgpMainNet
        subnetName: subnet2
      - name: BgpMainNetV6
        subnetName: subnet2
    nodes:
      edpm-r1-compute-0:
        hostName: edpm-r1-compute-0
        ansible:
          ansibleHost: '2620:cf:cf:aaab::100'
          ansibleVars:
            edpm_ovn_bgp_agent_local_ovn_peer_ips:
              - "2620:cf::100:64:1:1"
              - "2620:cf::100:65:1:1"
            edpm_frr_bgp_peers:
              - "2620:cf::100:64:1:1"
              - "2620:cf::100:65:1:1"
        networks:
          - defaultRoute: true
            fixedIP: '2620:cf:cf:aaab::100'
            name: CtlPlane
            subnetName: subnet1
          - name: InternalApi
            subnetName: subnet1
          - name: Storage
            subnetName: subnet1
          - name: Tenant
            subnetName: subnet1
          - name: Bgpnet0
            subnetName: subnet1
            fixedIP: "2620:cf::100:64:1:2"
          - name: Bgpnet1
            subnetName: subnet1
            fixedIP: "2620:cf::100:65:1:2"
          - name: Bgpnet0ipv4
            subnetName: subnet1
            fixedIP: "100.64.1.2"
          - name: Bgpnet1ipv4
            subnetName: subnet1
            fixedIP: "100.65.1.2"
          - name: Bgpmainnet
            subnetName: subnet1
            fixedIP: 99.99.1.2
          - name: BgpmainnetV6
            subnetName: subnet1
            fixedIP: f00d:f00d:f00d:f00d:99:99:1:2
    services:
      - download-cache
      - bootstrap
      - configure-network
      - install-os
      - configure-os
      - frr
      - validate-network
      - run-os
      - reboot-os
      - install-certs
      - ovn
      - neutron-metadata
      - ovn-bgp-agent
      - libvirt
      - nova
  nova:
    migration:
      ssh_keys:
        private: CHANGEME4
        public: CHANGEME5
