---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  # Set namespace to OpenStack on all namespaced objects without a namespace
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
    - path: metadata/name
      kind: Namespace
      create: true

secretGenerator:
  - name: bmc-secret
    behavior: create
    envs:
      - bmc-secret.env
    options:
      disableNameSuffixHash: true

resources:
  - baremetalhosts.yaml
  - provisioning.yaml

replacements:
  # Labels
  - source:
      kind: ConfigMap
      name: baremetalhost-values
      fieldPath: data.edpm-compute-0.labels
    targets:
      - select:
          kind: BareMetalHost
          name: edpm-compute-0
        fieldPaths:
          - metadata.labels
        options:
          create: true

  # Enable/Disable Metal3 Inspection
  - source:
      kind: ConfigMap
      name: baremetalhost-values
      fieldPath: data.metal3_inspection
    targets:
      - select:
          kind: BareMetalHost
        fieldPaths:
          - metadata.annotations.inspect\.metal3\.io
        options:
          create: true

  # BMC Configuration
  - source:
      kind: ConfigMap
      name: baremetalhost-values
      fieldPath: data.edpm-compute-0.bmc
    targets:
      - select:
          kind: BareMetalHost
          name: edpm-compute-0
        fieldPaths:
          - spec.bmc
        options:
          create: true

  # bootMACAddress
  - source:
      kind: ConfigMap
      name: baremetalhost-values
      fieldPath: data.edpm-compute-0.bootMACAddress
    targets:
      - select:
          kind: BareMetalHost
          name: edpm-compute-0
        fieldPaths:
          - spec.bootMACAddress
        options:
          create: true

  # rootDeviceHints
  - source:
      kind: ConfigMap
      name: baremetalhost-values
      fieldPath: data.edpm-compute-0.rootDeviceHints
    targets:
      - select:
          kind: BareMetalHost
          name: edpm-compute-0
        fieldPaths:
          - spec.rootDeviceHints
        options:
          create: true

  # preprovisioningNetworkData
  - source:
      kind: ConfigMap
      name: baremetalhost-values
      fieldPath: data.edpm-compute-0.preprovisioningNetworkData
    targets:
      - select:
          kind: Secret
          name: edpm-compute-0-preprovision-network-data
        fieldPaths:
          - stringData
        options:
          create: true
