# local-config: referenced, but not emitted by kustomize
#
# CHANGEME:
#
# - Change network_vlan_ranges based on EDPM OVS DPDK SRIOV HCI environment.
# - change numa_nodes in the neutron and neutron_tunnel section
# based on DPDK NIC's and NUMA alignment in the OVS DPDK SRIOV HCI compute node.
#
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  # --- Fields required by lib/control-plane ---
  preserveJobs: false
  tls:
    caBundleSecretName: ""

  # --- Below are VA/DT-specific data ---
  neutron:
    customServiceConfig: |
      [DEFAULT]
      global_physnet_mtu = 9000
      [ml2]
      mechanism_drivers = ovn,sriovnicswitch
      path_mtu = 0
      [ovn]
      vhost_sock_dir = /var/lib/vhost_sockets
      enable_distributed_floating_ip=False
      [ml2_type_vlan]
      network_vlan_ranges = dpdk1:206:209,dpdk2:206:209,sriov1,sriov2 # CHANGEME
      [ovs]
      igmp_snooping_enable = True
      [oslo_policy]
      policy_file=/etc/neutron/policy.d/policy.yaml
  ovn:
    ovnController:
      nicMappings:
        datacentre: ospbr
  telemetry:
    enabled: true
    template:
      ceilometer:
        enabled: true
  extraMounts:
    - extraVol:
        - propagation:
            - NeutronAPI
          extraVolType: Policy
          volumes:
            - name: neutron-policy
              configMap:
                name: neutron-policy
          mounts:
            - name: neutron-policy
              mountPath: /etc/neutron/policy.d
              readOnly: true
  nova:
    schedulerServiceTemplate:
      customServiceConfig: |
        [filter_scheduler]
        enabled_filters = AvailabilityZoneFilter,ComputeFilter,ComputeCapabilitiesFilter,ImagePropertiesFilter,ServerGroupAntiAffinityFilter,ServerGroupAffinityFilter,PciPassthroughFilter,NUMATopologyFilter,AggregateInstanceExtraSpecsFilter
