---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../../../dt/nova/nova02beta/edpm/nodeset2/
  # - https://github.com/openstack-k8s-operators/architecture/va/nfv/sriov/edpm/nodeset?ref=main
  ## It's possible to replace ../../../../../../va/nfv/sriov/edpm/nodeset/ with a git checkout URL as per:
  ## https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md

resources:
  - values.yaml

patches:
  - target:
      kind: OpenStackDataPlaneNodeSet
      name: openstack-edpm
    patch: |-
      - op: replace
        path: /metadata/name
        value: openstack-edpm-2
