---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  # Set namespace to OpenStack on all namespaced objects without a namespace
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
    - path: metadata/name
      kind: Namespace
      create: true

components:
  - ../../../../../lib/dataplane/nodeset2

resources:
  - baremetalset-password-secret.yaml
  - nova_ovs_dpdk_sriov.yaml
  - neutron_igmp.yaml

replacements:
  - source:
      kind: ConfigMap
      name: edpm-nodeset2-values
      fieldPath: data.root_password
    targets:
      - select:
          kind: Secret
          name: baremetalset-password-secret-2
        fieldPaths:
          - data.NodeRootPassword
        options:
          create: true

  # Nova compute CPU pinning customization
  - source:
      kind: ConfigMap
      name: edpm-nodeset2-values
      fieldPath: data.nova.compute.conf
    targets:
      - select:
          kind: ConfigMap
          name: ovs-dpdk-sriov-cpu-pinning-nova-2
        fieldPaths:
          - data.25-cpu-pinning-nova\.conf
        options:
          create: true
  # Nova compute PCI passthrough customization
  - source:
      kind: ConfigMap
      name: edpm-nodeset2-values
      fieldPath: data.nova.pci.conf
    targets:
      - select:
          kind: ConfigMap
          name: sriov-nova-2
        fieldPaths:
          - data.03-sriov-nova\.conf
        options:
          create: true
  - source:
      kind: ConfigMap
      name: edpm-nodeset2-values
      fieldPath: data.preProvisioned
    targets:
      - select:
          kind: OpenStackDataPlaneNodeSet
          name: openstack-edpm-2
        fieldPaths:
          - spec.preProvisioned
        options:
          create: true
  - source:
      kind: ConfigMap
      name: edpm-nodeset2-values
      fieldPath: data.baremetalSetTemplate
    targets:
      - select:
          kind: OpenStackDataPlaneNodeSet
          name: openstack-edpm-2
        fieldPaths:
          - spec.baremetalSetTemplate
        options:
          create: true
  # Neutron IGMP configuration
  - source:
      kind: ConfigMap
      name: edpm-nodeset2-values
      fieldPath: data.neutron.igmp.conf
    targets:
      - select:
          kind: ConfigMap
          name: neutron-igmp-2
        fieldPaths:
          - data.25-igmp\.conf
        options:
          create: true
